---
- name: Start Pterodactyl Wings
  block:
    - name: Create directories for Docker Compose
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ wings_data_dir }}/wings/logs"
        - "{{ wings_data_dir }}/wings/etc"

    - name: Create config.yml
      ansible.builtin.copy:
        content: ""
        force: false
        mode: "0600"
        dest: "{{ wings_data_dir }}/wings/etc/config.yml"

    - name: Create docker-compose.yml
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ wings_data_dir }}/docker-compose.yml"

    - name: Start pterodactyl wings
      community.docker.docker_compose:
        project_src: "{{ wings_data_dir }}"
