---
- name: Common tasks
  block:

    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Check whether cloud-init has been installed, and ensure manage_etc_hosts is disabled
      become: true
      block:
        - name: Ensure /etc/cloud/cloud.cfg exists
          stat:
            path: /etc/cloud/cloud.cfg
          register: cloud_init

        - name: Disable cloud-init manage_etc_hosts
          copy:
            content: "manage_etc_hosts: false"
            dest: /etc/cloud/cloud.cfg.d/99-pterodactyl.cfg
            mode: "0660"
          when: cloud_init.stat.exists

    - name: Add IP address of all hosts to all hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Install python3-pip
      become: true
      ansible.builtin.apt:
        name: python3-pip

    - name: Install and enable qemu-guest-agent
      become: true
      block:

      - name: Install qemu-guest-agent
        ansible.builtin.apt:
          name: qemu-guest-agent

      - name: Enable and start qemu-guest-agent
        ansible.builtin.systemd_service:
          name: qemu-guest-agent
          state: started
          enabled: true

    - name: Install pip and docker-compose
      ansible.builtin.import_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
            version: "6.1.3"
          - name: docker-compose

    - name: Install docker
      become: true
      ansible.builtin.import_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_user }}"


    - name: Create Pterodactyl network
      community.docker.docker_network:
        name: pterodactyl
        ipam_config:
          - subnet: 172.19.0.0/16
